version: '3.8'

services:
  web:
    build: .
    image: django_rest_voting_web
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - /usr/src/app/static
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./docker/.env.dev
    depends_on:
      db:
        condition: service_healthy
    container_name: django_rest_voting
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: