version: '3.8'

services:
  waiter:
    build: 
      context: .
      dockerfile: docker/Dockerfile_waiter
      target: waiter
    image: django_rest_votings_waiter
    depends_on:
      web:
        condition: service_healthy
  web:
    build: 
      context: .
      target: dev
    image: django_rest_votings_web
    command: >
      sh -c "python -m pip install -r requirements.dev.txt
             python -m pip install -r docker/requirements.dev.txt
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - /usr/src/app/static
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./docker/.env.dev
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:8000 && exit 0"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 30s
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: